# Generated by Django 4.2 on 2023-04-12 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hackathon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('background_image', models.ImageField(upload_to='hackathons/background_images/')),
                ('hackathon_image', models.ImageField(upload_to='hackathons/hackathon_images/')),
                ('submission_type', models.CharField(choices=[('image', 'Image'), ('file', 'File'), ('link', 'Link')], max_length=5)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('reward_prize', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('submission_type', models.CharField(choices=[('image', 'Image'), ('file', 'File'), ('link', 'Link')], max_length=5)),
                ('image_submission', models.ImageField(blank=True, null=True, upload_to='submissions/images/')),
                ('file_submission', models.FileField(blank=True, null=True, upload_to='submissions/files/')),
                ('link_submission', models.URLField(blank=True, null=True)),
                ('hackathon', models.ManyToManyField(related_name='submissions', to='hackathons.hackathon')),
            ],
        ),
    ]
